[package]
name = "mail_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = "1.0.187"
clap= "4.4.0"
color-eyre = "0.6.2"
thiserror = "1.0"
